apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"alist","app.kubernetes.io/name":"ix-chart"},"name":"alist","namespace":"ix-alist"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"alist","app.kubernetes.io/name":"ix-chart"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"alist","app.kubernetes.io/name":"ix-chart"}},"spec":{"containers":[{"args":["/opt/alist/alist admin set RANDOM_PASSWORD || true\n/opt/alist/alist server\n"],"command":["/bin/sh","-c"],"env":[{"name":"PUID","value":"1000"},{"name":"PGID","value":"1000"},{"name":"UMASK","value":"022"}],"image":"xhofe/alist:latest","name":"ix-chart","ports":[{"containerPort":5244,"hostPort":5244,"protocol":"TCP"}],"resources":{"requests":{"cpu":"10m","memory":"50Mi"}},"volumeMounts":[{"mountPath":"/opt/alist/data/nfs","name":"ix-host-path-alist-0"},{"mountPath":"/opt/alist/data/ISOs","name":"ix-host-path-alist-1"},{"mountPath":"/opt/alist/data","name":"alist-config"}]}],"hostNetwork":true,"volumes":[{"hostPath":{"path":"/mnt/foo/nfs"},"name":"ix-host-path-alist-0"},{"hostPath":{"path":"/mnt/foo/ISOs"},"name":"ix-host-path-alist-1"},{"hostPath":{"path":"/mnt/foo/z3/nfs"},"name":"ix-host-path-alist-2"},{"hostPath":{"path":"/var/lib/truenas-apps/alist","type":"DirectoryOrCreate"},"name":"alist-config"}]}}}}
  creationTimestamp: "2024-10-27T08:35:27Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: alist
    app.kubernetes.io/name: ix-chart
  name: alist
  namespace: ix-alist
  resourceVersion: "166190"
  uid: decc8be3-cf70-4696-9b70-2022eb3dd325
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: alist
      app.kubernetes.io/name: ix-chart
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: alist
        app.kubernetes.io/name: ix-chart
    spec:
      containers:
      - args:
        - |
          /opt/alist/alist admin set RANDOM_PASSWORD || true
          /opt/alist/alist server
        command:
        - /bin/sh
        - -c
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "022"
        image: xhofe/alist:latest
        imagePullPolicy: Always
        name: ix-chart
        ports:
        - containerPort: 5244
          hostPort: 5244
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/alist/data/nfs
          name: ix-host-path-alist-0
        - mountPath: /opt/alist/data/ISOs
          name: ix-host-path-alist-1
        # - mountPath: /opt/alist/data/bar
        #   name: ix-host-path-alist-2
        - mountPath: /opt/alist/data
          name: alist-config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/foo/nfs
          type: ""
        name: ix-host-path-alist-0
      - hostPath:
          path: /mnt/foo/ISOs
          type: ""
        name: ix-host-path-alist-1
      # - hostPath:
      #     path: /mnt/bar
      #     type: ""
      #   name: ix-host-path-alist-2
      - hostPath:
          path: /var/lib/truenas-apps/alist
          type: DirectoryOrCreate
        name: alist-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-10-27T08:35:38Z"
    lastUpdateTime: "2024-10-27T08:35:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-10-27T08:35:27Z"
    lastUpdateTime: "2024-10-27T08:35:38Z"
    message: ReplicaSet "alist-8c976676c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
