services:
  # Databases (as before)
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strongpostgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-db-network
    profiles:
      - always

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-strongmysql}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shared-db-network
    profiles:
      - always

  # Redis with persistence
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-strongredis} --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - shared-db-network
    profiles:
      - always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-strongredis}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis UI (Optional)
  redis-commander:
    image: rediscommander/redis-commander
    restart: unless-stopped
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      REDIS_HOSTS: redis:redis:6379:0:${REDIS_PASSWORD:-strongredis}
      HTTP_USER: admin
      HTTP_PASSWORD: ${REDIS_COMMANDER_PASSWORD:-admin}
    networks:
      - shared-db-network
    profiles:
      - admin

  # Other admin tools as before...
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - shared-db-network
    profiles:
      - admin

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-80}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@admin.net}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-adminpass}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - shared-db-network
    profiles:
      - admin

networks:
  shared-db-network:
    name: shared-db-network

volumes:
  postgres-data:
    name: shared-postgres-data
  mysql-data:
    name: shared-mysql-data
  pgadmin-data:
    name: shared-pgadmin-data
  redis-data:
    name: shared-redis-data
